export const ADD_TO_USER_TO_STATE = 'ADD_TO_USER_TO_STATE';
export const REMOVE_USER_FROM_STATE = 'REMOVE_USER_FROM_STATE';
export const UPDATE_USER_FAVORITES = 'UPDATE_USER_FAVORITES';
export const ADD_ITEM_TO_STATE_CART = 'ADD_ITEM_TO_STATE_CART';
export const ADD_CART_STATE = 'ADD_CART_STATE';
export const REMOVE_FROM_CARD = 'REMOVE_FROM_CARD';
export const ADJUST_QUANTITY = 'ADJUST_QUANTITY';