export const ADD_TO_USER_TO_STATE = 'ADD_TO_USER_TO_STATE';
export const REMOVE_USER_FROM_STATE = 'REMOVE_USER_FROM_STATE';
export const UPDATE_USER_FAVORITES = 'UPDATE_USER_FAVORITES';
export const ADD_TO_CARD = 'ADD_TO_CARD';
export const REMOVE_FROM_CARD = 'REMOVE_FROM_CARD';
export const ADJUST_QUANTITY = 'ADJUST_QUANTITY';